### ISSUE TITLE
rename repo

### ISSUE THREAD

**Issue by ahwagner** [biocommons/biocommons.seqrepo#114]
All other biocommons software products are named for the product, not the parent org, except seqrepo. I propose we rename this repo to simply `seqrepo` for consistency.

**Comment by reece** [comment]
The rationale for this is to name the repo after the package name. From that point of view, the naming is consistent.

Although I might agree that this isn't optimal, I also think that renaming is a very low-value and high-risk (of not working, of confusion in people, of discontinuity in releases), so just isn't worth it.

So, I'd like to not rename.

**Comment by ahwagner** [comment]
That sounds reasonable to me. Adding the `question` tag so we can refer back to this issue as rationale.
