### ISSUE TITLE
`seqrepo` cli not installed in 0.6.6 and 0.6.7

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.seqrepo#138]
**Describe the bug**

Some [change between 0.6.5 and 0.6.6](https://github.com/biocommons/biocommons.seqrepo/compare/0.6.5...0.6.6) causes the seqrepo command line script to not be installed. This issue affects local (dev) installation and the pypi packages. 0.6.7 has the same issue.

**To Reproduce**
1. Create a venv
2. `pip uninstall biocommons.seqrepo`, `pip install biocommons.seqrepo==0.6.7`, then `seqrepo`. You should see `seqrepo: command not found`.
3. Try again with 0.6.6. Same outcome.
4. Try again with 0.6.5. seqrepo should start and show the help message.
5. The same occurs in a development environment with something like `git checkout 0.6.7; pip uninstall biocommons.seqrepo; pip install -e .[dev]`. 

**Expected behavior**

The seqrepo command line tool should be installed in all versions.

@korikuzma @jsstevenson @andreasprlic

**Comment by reece** [comment]
I have been unable to isolate the underlying cause, but switching from setup.cfg to pyproject.toml seems likely.

Note that biocommons.example works as expected.

**Comment by jsstevenson** [comment]
Just on my phone between baby naps, but the `blame` definitely points my way. Maybe setuptools is unhappy when `entry_points` is still defined in setup.py/cfg but other parts of the build specs have been moved to `pyproject.toml`? Either way, an overwrite of my last PR with the stuff in the example template is overdue, so if that also fixes this issue, then that's two birds at once

**Comment by reece** [comment]
Found it. The error was my merge at ee80d92a805c32cb6e63e839a95d794259cedde9. I'll fix.

**Comment by korikuzma** [comment]
@larrybabb I think this is the issue you were encountering today.
