### ISSUE TITLE
--update-latest CLI flag is not pulling in the most recent version

### ISSUE THREAD

**Issue by quinnwai** [biocommons/biocommons.seqrepo#140]
When downloading the seqrepo db by CLI with `seqrepo --root-directory ~/seqrepo/ pull --update-latest`, the command wants to pull in `2021-01-29/` even when I have `2023-09-18/` already downloaded. I tested this locally (MacOS Ventura 13.2.1) as well as in the CLI on Terra.

Expected that either nothing would be downloaded or a more recent version would be downloaded

Let me know if I can provide more info!

**Comment by korikuzma** [comment]
@quinnwai I believe this is due to #126 (see thread)

**Comment by reece** [comment]
I expect this to work now, including the latest symlink. Closing.

**Comment by quinnwai** [comment]
Just checked, it worked! Thanks for the update
