### ISSUE TITLE
eliminate mirrors requirement and "tighten" update cycle

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.seqrepo#21]
The seqrepo loading process currently expects from mirrors-ncbi. That process is cumbersome and requires lots of disk space.

To improve currency of seqrepo data, implement a new loading process that downloads data, loads, and then discards the download. The goal is to eliminate long-term mirroring.

Ideas to consider:
* streaming loading
* how to support multiple sources (e.g., NCBI, Ensembl-xx, LRG)
* builder as docker image
* exact inputs and outputs to process. e.g., does this operate on master, or on a snapshot? Does it generate a new snapshot?
* where to build?

**Comment by andreasprlic** [comment]
+1

**Comment by reece** [comment]
Update: I've got streaming builds working on new seqrepo instances for NCBI, LRG, and Ensembl (any version). I will update `master` and create a new snapshot in the next day or so.

@andreasprlic
