### ISSUE TITLE
Permission issue when run using docker

### ISSUE THREAD

**Issue by andreas-invitae** [biocommons/biocommons.seqrepo#30]
Hi Reece,

I tried to get a local version of seqrepo setup using docker (under OSX). When trying to share my local seqrepo folder using 
`docker run -v /usr/local/share/seqrepo:/usr/local/share/seqrepo  biocommons/seqrepo`
rsync is running into permission problems:
`rsync: recv_generator: mkdir "/usr/local/share/seqrepo/2018-08-21.et6u24wj/sequences" failed: Permission denied (13)`

After some googling I managed to work around this by using:
`docker run -v /usr/local/share/seqrepo:/usr/local/share/seqrepo --user 1000:50 biocommons/seqrepo`

With this, seqrepo starts to download files, However after the downloads are complete, the renaming of the folder fails with
`PermissionError: [Errno 13] Permission denied: '/usr/local/share/seqrepo/2018-08-21.a6_3p6gn' -> '/usr/local/share/seqrepo/2018-08-21’`

Note: I made sure that `/usr/local/share/seqrepo/` is configured in docker as a shared folder and the `seqrepo` folder has global write permissions.

Any thoughts?

Thanks,
Andreas

**Comment by andreas-invitae** [comment]
Yea, I am also suspecting some OSX specifics here. This is what I get for docker run -t ...:

```
docker run -t -i -e SEQREPO_DATA_RELEASE=2010-00-00 -v /tmp/sr1:/usr/local/share/seqrepo biocommons/seqrepo
receiving incremental file list
created directory /usr/local/share/seqrepo/2010-00-00.qxfjyef5
rsync: recv_generator: mkdir "/usr/local/share/seqrepo/2010-00-00.qxfjyef5/sequences/2016" failed: Permission denied (13)
*** Skipping any contents from this failed directory ***
./
sequences/
sequences/2016/
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [generator=3.1.2]
Traceback (most recent call last):
  File "/usr/local/bin/seqrepo", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/biocommons/seqrepo/cli.py", line 469, in main
    opts.func(opts)
  File "/usr/local/lib/python3.6/dist-packages/biocommons/seqrepo/cli.py", line 348, in pull
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/rsync', '-aHP', '--no-motd', 'dl.biocommons.org::seqrepo/2010-00-00/', '/usr/local/share/seqrepo/2010-00-00.qxfjyef5']' returned non-zero exit status 23.
```
then the next step:
```
 ls -lR /tmp/sr1
total 0
drwxr-xr-x@ 3 aprlic  wheel  96 Sep 10 20:44 2010-00-00.qxfjyef5

/tmp/sr1/2010-00-00.qxfjyef5:
total 0
dr-xr-xr-x@ 2 aprlic  wheel  64 Aug 27  2016 sequences

/tmp/sr1/2010-00-00.qxfjyef5/sequences:
```

**Comment by reece** [comment]
What's your uid? biocommons (on minion) is 1004. I assumed that you were 1000 from the --user in the original post.  I ask because the files above are owned by aprlic, so there are two possibilities: 1) you happen to also be 1004, 2) some actor intervened on your machine to make them owned by you. It's strange that the sequences directory could be created, but not the 2016 directory within it.

This smells specific to docker on a Mac.

**Comment by andreas-invitae** [comment]
`uid=501(aprlic)`. That means that this works:

```docker run --user 501 -t -i -e SEQREPO_DATA_RELEASE=2010-00-00 -v /tmp/sr1:/usr/local/share/seqrepo biocommons/seqrepo
receiving incremental file list
created directory /usr/local/share/seqrepo/2010-00-00.a_g1aw4z
./
sequences/
sequences/2016/
sequences/2016/0827/
sequences/2016/0827/205216/
sequences/2016/0827/205216/1472331136.5661852.fa.bgz.gzi
             24 100%   23.44kB/s    0:00:00 (xfr#1, to-chk=0/6)
```

**Comment by reece** [comment]
Check out https://docs.docker.com/docker-for-mac/osxfs/
and especially https://github.com/docker/for-mac/issues/2657#issuecomment-371210749

I don't understand those explanations well enough to have predicted the behavior you observe, but it seems clear that docker on Mac is futzing with ownership in order to avoid root escalation and that this is likely the source of your troubles.

I would like seqrepo to work on mac, but I don't have a mac to make that happen.

**Comment by andreas-invitae** [comment]
thanks will take a look!

**Comment by reece** [comment]
Great! Would you please try with `--user $(id -u):$(id -g)` ? If that works, I'll make that the recommended command line.

**Comment by andreas-invitae** [comment]
`docker run --user $(id -u):$(id -g) -t -i -e SEQREPO_DATA_RELEASE=2010-00-00 -v /tmp/sr1:/usr/local/share/seqrepo biocommons/seqrepo` works!
