### ISSUE TITLE
Permission denied on pull

### ISSUE THREAD

**Issue by viv-1** [biocommons/biocommons.seqrepo#37]
Hello,

I am trying to download seqrepo file with the command : `seqrepo -r seqrepo/ pull`
The rsync is failing with error message :
```
rsync: change_dir "/2018-10-03" (in seqrepo) failed: Permission denied (13)
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]
```

Apparently there is a right problem on the server.

Best regards,

Vivien

**Comment by reece** [comment]
Thanks @viv-1 for the report. Please try now and comment here. If it works, please close the issue. Sorry for the problem!

**Comment by viv-1** [comment]
Hello @reece,

I tried again and it worked !
Thanks for your reactivity.

Best regards,

Vivien
