### ISSUE TITLE
improve test coverage

### ISSUE THREAD

**Issue by reece** [biocommons/biocommons.seqrepo#45]
Test coverage is a measly 63%. Write tests to get to at least 90%.

Current coverage on master branch (live update): [![Coverage Status](https://coveralls.io/repos/github/biocommons/biocommons.seqrepo/badge.svg?branch=master)](https://coveralls.io/github/biocommons/biocommons.seqrepo?branch=master)

**Comment by khmccurdy** [comment]
Note from tonight's presentation: Most of the missing tests are for Python 2 legacy code, which will be phased out in the coming months.

**Comment by xke** [comment]
Just wanted to note these items to resolve potential errors with "make devready" on a Mac:
- To fix "xcrun: error:", install Xcode and components from the Mac App Store
- For environments wit Python 3.7, update Makefile to set "PYV:=3.7" and "venv/3.5 venv/3.6 venv/3.7: venv/%:"

**Comment by reece** [comment]
@xke Thanks for the notes. I just added notes to the README re: xcode and update the Makefile to support 3.7 and, by default, create a venv for whatever version of Python 3 is found by default.

**Comment by khmccurdy** [comment]
Status report as of 1-19-2019, not including Python 2 modules:
`cli.py` : `23% coverage (246 lines untested)` (though ispashayev's PR should improve this somewhat)
`fastadir/fabgz.py` : `91% (8)`
`fastadir/fastadir.py` : `90% (10)`
`seqrepo.py` : `97% (4)`

**Comment by khmccurdy** [comment]
Those were from a fresh pull on my end, no new changes were made.

**Comment by reece** [comment]
You can also see coverage at https://coveralls.io/github/biocommons/biocommons.seqrepo, which you can access from the [![Coverage Status](https://coveralls.io/repos/github/biocommons/biocommons.seqrepo/badge.svg?branch=master)](https://coveralls.io/github/biocommons/biocommons.seqrepo?branch=master) badge.

![image](https://user-images.githubusercontent.com/109453/51446305-2e27b500-1cc5-11e9-8d15-00010a0a01b3.png)
