### ISSUE TITLE
ssl certs for dl.biocommons.org

### ISSUE THREAD

**Issue by jhl667** [biocommons/biocommons.seqrepo#85]
Could this be added?  Our institution does not allow connections to non-https links.

**Comment by reece** [comment]
Done!

Way easier than I expected (thanks to https://www.nginx.com/blog/using-free-ssltls-certificates-from-lets-encrypt-with-nginx/)

**Comment by jhl667** [comment]
awesome, you are quick!!! I wish I hadn't already done the workaround of downloading outside of vpn to my local machine then transferring where I wanted it, lol

**Comment by reece** [comment]
Well, the funny thing is that I had drafted a "no, sorry, can't do this now" sort of reply. Then I thought I should see how hard it would be and whether :443 was even open. Way easier than expected. Cheers.
