### ISSUE TITLE
Unable to get the data '2021-01-05' in seqrepo.

### ISSUE THREAD

**Issue by git4waki** [biocommons/biocommons.seqrepo#93]
**Problem**
Unable to get the data '2021-01-05' in seqrepo.

**Command**
$ seqrepo -r my_local_seqrepo_dir pull

**Error message**
receiving incremental file list
rsync: change_dir "/2021-01-05" (in seqrepo) failed: Permission denied (13)
.........

Is 'http://dl.biocommons.org/seqrepo/2021-01-05/' directory not yet available?

Best regards,

Kazunori Waki

**Comment by jsstevenson** [comment]
Hi, 

I haven't been able to reproduce this (four years later... ) but please feel free to reopen if it continues to be a problem.
