### ISSUE TITLE
Look into improving genomic query times

### ISSUE THREAD

**Issue by korikuzma** [biocommons/biocommons.seqrepo#97]
Genomic accession queries such as `seqrepo.fetch('NC_000007.14')` are slow (~1s) compared to protein and transcript accession queries such as `seqrepo.fetch('NM_000433.4')` and `seqrepo.fetch('NP_004324.2')`  (~5ms). This is likely due to very large sequences.

@ahwagner suggested looking into [htslib](https://github.com/samtools/htslib) or splitting sequences and indexing them.

**Comment by reece** [comment]
Seqrepo already uses pysam's FastaFile, which use htslib. 

Depending on the size of the slice, 1s doesn't seem so bad.

Looking up a sequence by accession entails two SQLite queries: one to find the internal sequence id and another to find which file that sequence id is in. Both of these should use indexes. Perhaps these are slow.

Perhaps we should profile the code to find opportunities for improvement.

**Comment by korikuzma** [comment]
You're right. I realized I was not querying SeqRepo correctly for our project's purposes, but I'm still curious to see if it is possible to improve genomic query times. I will try to look into this when I have some free time.
